spring:
  profiles:
    active:
      - cat
      - ES
      - prod
di:
  username: YmlUsername
  password: YmlPassword
  jdbcUrl: YmlJdbcUrl

---
spring:
  config:
    activate:
      on-profile: prod
di:
  username: YmlProdUsername
  password: YmlProdPassword
  jdbcUrl: YmlProdJdbcUrl